// javascript/langue.js

const translations = {
    fr: {
        title: "Tutoriel d’installation et de configuration de GLPI sur Debian 12 (VMware)",
        sommaireTitle: "Sommaire",
        sommaireItem1: "1. Introduction à GLPI",
        sommaireItem2: "2. Prérequis officiels de GLPI",
        sommaireItem3: "3. Préparation du serveur Debian 12",
        sommaireItem4: "4. Installation du socle LAMP",
        sommaireItem5: "5. Configuration sécurisée de MariaDB",
        sommaireItem6: "6. Téléchargement et préparation de GLPI",
        sommaireItem7: "7. Configuration d’Apache avec VirtualHost",
        sommaireItem8: "8. Configuration de PHP-FPM et extensions requises",
        sommaireItem9: "9. Installation via navigateur web",
        sommaireItem10: "10. Première connexion et sécurité",
        sommaireItem11: "11. Bonnes pratiques post-installation",
        sommaireItem12: "12. Conclusion",
        etape1Title: "1. Introduction à GLPI",
        etape1Text1: "GLPI (Gestionnaire Libre de Parc Informatique) est un logiciel libre de gestion de parc informatique, offrant une solution complète pour la gestion des équipements (ordinateurs, téléphones, périphériques), le suivi des tickets de support, ainsi que l’administration des contrats, licences et ressources matérielles.",
        etape1Text2: "Depuis sa création en 2003, GLPI s’est imposé comme une solution fiable et largement adoptée. Ce tutoriel vous guide pas à pas dans son installation sur <strong>Debian 12</strong> avec un environnement <strong>LAMP</strong> sous VMware.",
        etape1H3: "Présentation de GLPI",
        etape2Title: "2. Pré-requis pour l'installation de GLPI",
        etape2Text1: "Avant de procéder à l’installation, il est important de vérifier que votre environnement répond aux prérequis nécessaires. GLPI nécessite un serveur web, PHP et une base de données pour fonctionner correctement. Sur un système Linux, cela correspond généralement à une architecture LAMP. GLPI est compatible avec plusieurs serveurs web, notamment :",
        etape2List1: "Apache2, Nginx, Lighttpd et IIS",
        etape2H5_1: "Versions requises",
        etape2H7_1: "● PHP",
        etape2PhpList: "Version : 8.2",
        etape2H7_2: "● Base de données",
        etape2DbList1: "MySQL : version 5.1 minimum",
        etape2DbList2: "MariaDB : version 10.2 minimum",
        etape2Text2: "Notez également que plusieurs extensions PHP doivent être installées pour assurer le bon fonctionnement de GLPI.",
        etape2Text3: "La dernière version disponible à ce jour, <strong>GLPI 10.0.10</strong>, introduit le support de PHP 8.3 (future version stable) et MySQL 8.1, tout en corrigeant de nombreuses vulnérabilités critiques.",
        etape2Text4: "Pour cette démonstration, nous utiliserons une machine sous <strong>Debian 12</strong>, sur laquelle nous installerons <strong>Apache2</strong>, <strong>PHP 8.3</strong> et <strong>MariaDB</strong>.",
        etape2Text5: "Pour plus de détails, vous pouvez consulter la <a href=\"https://glpi-install.readthedocs.io/en/latest/prerequisites.html\" target=\"_blank\">documentation officielle des prérequis de GLPI</a>.",
        etape3Title: "3. Préparation du serveur Debian 12",
        etape3Text1: "Commençons par l'installation par une mise à jour des paquets sur la machine Debian 12. Pensez également à lui attribuer une adresse IP et à effectuer la configuration du système",
        etape4Title: "4. Installation du socle LAMP",
        etape4Text1: "La première grande étape consiste à installer les paquets du socle LAMP : Linux Apache2 MariaDB PHP. Sous Debian 12, qui est la dernière version stable de Debian, PHP 8.2 est distribué par défaut dans les dépôts officiels. Commençons par installer ces trois paquets :",
        etape4Text2: "Puis, nous allons installer toutes les extensions nécessaires au bon fonctionnement de GLPI.",
        etape4Text3: "Ces commandes vont permettre de récupérer les versions de ces extensions pour PHP 8.2.",
        etape4Text4: " Si vous envisagez d'associer GLPI avec un annuaire LDAP comme l'Active Directory, vous devez installer l'extension LDAP de PHP. Sinon, ce n'est pas nécessaire et vous pouvez le faire par la suite, si besoin.",
        etape4Text5: "Nous venons d'installer Apache2, MariaDB, PHP et un ensemble d'extensions.",
        etape5Title: "5. Configuration sécurisée de MariaDB",
        etape5Text1: "Nous allons préparer MariaDB pour qu'il puisse héberger la base de données de GLPI. La première action à effectuer, c'est d'exécuter la commande ci-dessous pour effectuer le minimum syndical en matière de sécurisation de MariaDB.",
        etape5Text2: "Vous serez invité à changer le mot de passe root, mais aussi à supprimer les utilisateurs anonymes, désactiver l'accès root à distance, etc... Tout est bien expliqué. Voici un exemple sur mon serveur pour vous guider :",
        etape5Text3: "Ensuite, nous allons créer une base de données dédiée pour GLPI et celle-ci sera accessible par un utilisateur dédié. Hors de question d'utiliser le compte root de MariaDB : une base de données = un utilisateur. Connectez-vous à votre instance MariaDB :",
        etape5Text4: "Saisissez le mot de passe root de MariaDB, que vous venez de définir à l'étape précédente.",
        etape5Text5: "Puis, nous allons exécuter les requêtes SQL ci-dessous pour créer la base de données \"db23_glpi\" ainsi que l'utilisateur \"glpi_adm\" avec le mot de passe \"MotDePasseRobuste\" (que vous changez, bien sûr). Cet utilisateur aura tous les droits sur cette base de données (et uniquement sur celle-ci).",
        etape5Text6: "Ce qui donne :",
        etape5Text7: "Voilà, la base de données prête.",
        etape6Title: "6. Téléchargement et préparation de GLPI",
        etape6Text1: "La prochaine étape consiste à télécharger l'archive \".tgz\" qui contient les sources d'installation de GLPI. A partir du GitHub de GLPI, récupérez le lien vers la dernière version. Ici, c'est la version GLPI 10.0.10 qui est installée.",
        etape6Text2: "Puis, nous allons exécuter la commande ci-dessous pour décompresser l'archive .tgz dans le répertoire \"/var/www/\", ce qui donnera le chemin d'accès \"/var/www/glpi\" pour GLPI.",
        etape6Text3: "Nous allons définir l'utilisateur \"www-data\" correspondant à Apache2, en tant que propriétaire sur les fichiers GLPI.",
        etape6Text4: "Ensuite, nous allons devoir créer plusieurs dossiers et sortir des données de la racine Web (/var/www/glpi) de manière à les stocker dans les nouveaux dossiers que nous allons créer. Ceci va permettre de faire une installation sécurisée de GLPI, qui suit les recommandations de l'éditeur.",
        etape6H5_1: "Le répertoire /etc/glpi",
        etape6Text5: "Commencez par créer le répertoire \"/etc/glpi\" qui va recevoir les fichiers de configuration de GLPI. Nous donnons des autorisations à www-data sur ce répertoire car il a besoin de pouvoir y accéder.",
        etape6Text6: "Puis, nous allons déplacer le répertoire \"config\" de GLPI vers ce nouveau dossier :",
        etape6H5_2: "Le répertoire /var/lib/glpi",
        etape6Text7: "Répétons la même opération avec la création du répertoire \"/var/lib/glpi\" :",
        etape6Text8: "Dans lequel nous déplaçons également le dossier \"files\" qui contient la majorité des fichiers de GLPI : CSS, plugins, etc.",
        etape6H5_3: "Le répertoire /var/log/glpi",
        etape6Text9: "Terminons par la création du répertoire \"/var/log/glpi\" destiné à stocker les journaux de GLPI. Toujours sur le même principe :",
        etape6Text10: "Nous n'avons rien à déplacer dans ce répertoire.",
        etape6H5_4: "Créer les fichiers de configuration",
        etape6Text11: "Nous devons configurer GLPI pour qu'il sache où aller chercher les données. Autrement dit, nous allons déclarer les nouveaux répertoires fraichement créés",
        etape6Text12: "Nous allons créer ce premier fichier :",
        etape6Text13: "Afin d'ajouter le contenu ci-dessous qui indique le chemin vers le répertoire de configuration :",
        etape6Text14: "Ensuite, nous allons créer ce second fichier :",
        etape6Text15: "Afin d'ajouter le contenu ci-dessous permettant de déclarer deux variables permettant de préciser les chemins vers les répertoires \"files\" et \"log\" que l'on a préparé précédemment.",
        etape6Text16: "Voilà, cette étape est terminée.",
        etape7Title: "7. Configuration d’Apache avec VirtualHost",
        etape7Text1: "Passons à la configuration du serveur web Apache2. Nous allons créer un nouveau fichier de configuration qui va permettre de configurer le VirtualHost dédié à GLPI.",
        etape7Text2: "Ce qui donne la configuration suivante :",
        etape7Text3: "Quand la configuration est prête, enregistrez le fichier.",
        etape7Text4: "Puis, nous allons activer ce nouveau site dans Apache2 :",
        etape7Text5: "Nous en profitons également pour désactiver le site par défaut car il est inutile :",
        etape7Text6: "Nous allons aussi activer le module \"rewrite\" (pour les règles de réécriture) car on l'a utilisé dans le fichier de configuration du VirtualHost (RewriteCond / RewriteRule).",
        etape7Text7: "Il ne reste plus qu'à redémarrer le service Apache2 :",
        etape8Title: "8. Configuration de PHP-FPM et extensions requises",
        etape8Text1: "Pour utiliser PHP en tant que moteur de scripts avec Apache2, il y a deux possibilités : utiliser le module PHP pour Apache2 (libapache2-mod-php8.2) ou utiliser PHP-FPM.",
        etape8Text2: "Il est recommandé d'utiliser PHP-FPM car il est plus performant et se présente comme un service indépendant. Dans l'autre mode, chaque processus Apache2 exécute son propre moteur de scripts PHP.",
        etape8Text3: "Si vous souhaitez utiliser PHP-FPM, suivez les étapes ci-dessous. Sinon, passez à la suite mais veillez à configurer l'option \"session.cookie_httponly\" évoquée ci-dessous.",
        etape8Text4: "Nous allons commencer par installer PHP8.2-FPM avec la commande suivante :",
        etape8Text5: "Puis, nous allons activer deux modules dans Apache et la configuration de PHP-FPM, avant de recharger Apache2 :",
        etape8Text6: "Pour configurer PHP-FPM pour Apache2, nous n'allons pas éditer le fichier \"/etc/php/8.2/apache2/php.ini\" mais plutôt ce fichier :",
        etape8Text7: "Dans ce fichier, recherchez l'option \"session.cookie_httponly\" et indiquez la valeur \"on\" pour l'activer, afin de protéger les cookies de GLPI.",
        etape8Text8: "Enregistrez le fichier quand c'est fait. Par la suite, vous pourriez être amené à effectuer d'autres modifications, notamment pour augmenter la taille des uploads sur GLPI, etc. Pour appliquer les modifications, nous devons redémarrer PHP-FPM :",
        etape8Text9: "Pour finir, nous devons modifier notre VirtualHost pour préciser à Apache2 que PHP-FPM doit être utilisé pour les fichiers PHP :",
        etape8Text10: "Voici un exemple :",
        etape8Text11: "Quand c'est fait, relancer Apache2 :",
        etape9Title: "9. Installation via navigateur web",
        etape9Text1: "Pour effectuer l'installation de GLPI, Accédez à <code>http://IP_DE_VOTRE_VM</code> et suivez les étapes :",
        etape9List1: "Choix de la langue",
        etape9List2: "Vérification des prérequis (tous doivent être en vert)",
        etape9List3: "Connexion à la base : <code>glpi_db</code>, utilisateur <code>glpi_user</code>",
        etape9List4: "Création des tables",
        etape9List5: "Fin de l’installation",
        etape9Text2: "<strong>⚠️ Sécurité :</strong> Supprimez immédiatement le script d’installation :",
        etape10Title: "10. Première connexion et sécurité",
        etape10Text1: "Comptes par défaut :",
        etape10List1: "<strong>Admin</strong> : <code>glpi</code> / <code>glpi</code>",
        etape10List2: "<strong>Technicien</strong> : <code>tech</code> / <code>tech</code>",
        etape10List3: "<strong>Utilisateur normal</strong> : <code>normal</code> / <code>normal</code>",
        etape10List4: "<strong>Post-only</strong> : <code>post-only</code> / <code>postonly</code>",
        etape10Text2: "➡️ Changez **tous les mots de passe** après la première connexion.",
        etape11Title: "11. Bonnes pratiques post-installation",
        etape11List1: "🔐 Activer HTTPS avec Let’s Encrypt",
        etape11List2: "🔄 Mettre à jour régulièrement GLPI et PHP",
        etape11List3: "💾 Sauvegarder la base : <code>mysqldump -u root -p glpi_db > /backup/glpi_$(date +%F).sql</code>",
        etape11List4: "🧩 Installer des plugins utiles : FusionInventory, LDAP, PDF, etc.",
        etape11List5: "🛡️ Restreindre l’accès à l’interface d’admin par IP",
        etape12Title: "12. Conclusion",
        etape12Text1: "Vous disposez maintenant d’une instance sécurisée et fonctionnelle de GLPI sur Debian 12. Ce système vous permet de gérer efficacement votre parc informatique, vos tickets d’assistance et vos ressources.",
        etape12Text2: "Pour aller plus loin : intégration LDAP, monitoring, automatisation des inventaires avec FusionInventory."
    },
    en: {
        title: "Tutorial for Installation and Configuration of GLPI on Debian 12 (VMware)",
        sommaireTitle: "Table of Contents",
        sommaireItem1: "1. Introduction to GLPI",
        sommaireItem2: "2. Official GLPI Prerequisites",
        sommaireItem3: "3. Preparing the Debian 12 Server",
        sommaireItem4: "4. Installing the LAMP Stack",
        sommaireItem5: "5. Secure MariaDB Configuration",
        sommaireItem6: "6. Downloading and Preparing GLPI",
        sommaireItem7: "7. Apache Configuration with VirtualHost",
        sommaireItem8: "8. PHP-FPM Configuration and Required Extensions",
        sommaireItem9: "9. Installation via Web Browser",
        sommaireItem10: "10. First Login and Security",
        sommaireItem11: "11. Post-Installation Best Practices",
        sommaireItem12: "12. Conclusion",
        etape1Title: "1. Introduction to GLPI",
        etape1Text1: "GLPI (Free IT Asset Manager) is an open-source software for IT asset management, offering a complete solution for managing equipment (computers, phones, peripherals), tracking support tickets, as well as administering contracts, licenses, and hardware resources.",
        etape1Text2: "Since its creation in 2003, GLPI has established itself as a reliable and widely adopted solution. This tutorial guides you step by step through its installation on <strong>Debian 12</strong> with a <strong>LAMP</strong> environment under VMware.",
        etape1H3: "GLPI Presentation",
        etape2Title: "2. Prerequisites for GLPI Installation",
        etape2Text1: "Before proceeding with the installation, it is important to check that your environment meets the necessary prerequisites. GLPI requires a web server, PHP, and a database to function properly. On a Linux system, this generally corresponds to a LAMP architecture. GLPI is compatible with several web servers, including:",
        etape2List1: "Apache2, Nginx, Lighttpd, and IIS",
        etape2H5_1: "Required Versions",
        etape2H7_1: "● PHP",
        etape2PhpList: "Version: 8.2",
        etape2H7_2: "● Database",
        etape2DbList1: "MySQL: version 5.1 minimum",
        etape2DbList2: "MariaDB: version 10.2 minimum",
        etape2Text2: "Note also that several PHP extensions must be installed to ensure GLPI works properly.",
        etape2Text3: "The latest version available to date, <strong>GLPI 10.0.10</strong>, introduces support for PHP 8.3 (future stable version) and MySQL 8.1, while fixing numerous critical vulnerabilities.",
        etape2Text4: "For this demonstration, we will use a machine running <strong>Debian 12</strong>, on which we will install <strong>Apache2</strong>, <strong>PHP 8.3</strong>, and <strong>MariaDB</strong>.",
        etape2Text5: "For more details, you can consult the <a href=\"https://glpi-install.readthedocs.io/en/latest/prerequisites.html\" target=\"_blank\">official GLPI prerequisites documentation</a>.",
        etape3Title: "3. Preparing the Debian 12 Server",
        etape3Text1: "Let's start the installation with an update of the packages on the Debian 12 machine. Also remember to assign it an IP address and perform the system configuration",
        etape4Title: "4. Installing the LAMP Stack",
        etape4Text1: "The first major step is to install the LAMP stack packages: Linux Apache2 MariaDB PHP. Under Debian 12, which is the latest stable version of Debian, PHP 8.2 is distributed by default in the official repositories. Let's start by installing these three packages:",
        etape4Text2: "Then, we will install all the extensions necessary for GLPI to function properly.",
        etape4Text3: "These commands will retrieve the versions of these extensions for PHP 8.2.",
        etape4Text4: " If you plan to associate GLPI with an LDAP directory like Active Directory, you must install the PHP LDAP extension. Otherwise, it is not necessary and you can do it later if needed.",
        etape4Text5: "We have just installed Apache2, MariaDB, PHP and a set of extensions.",
        etape5Title: "5. Secure MariaDB Configuration",
        etape5Text1: "We will prepare MariaDB so that it can host the GLPI database. The first action to perform is to run the command below to perform the minimum security for MariaDB.",
        etape5Text2: "You will be prompted to change the root password, but also to remove anonymous users, disable remote root access, etc... Everything is well explained. Here is an example on my server to guide you:",
        etape5Text3: "Then, we will create a dedicated database for GLPI and it will be accessible by a dedicated user. No way to use the MariaDB root account: one database = one user. Connect to your MariaDB instance:",
        etape5Text4: "Enter the MariaDB root password, which you just defined in the previous step.",
        etape5Text5: "Then, we will execute the SQL queries below to create the \"db23_glpi\" database as well as the \"glpi_adm\" user with the password \"MotDePasseRobuste\" (which you change, of course). This user will have all rights on this database (and only on this one).",
        etape5Text6: "Which gives:",
        etape5Text7: "There, the database is ready.",
        etape6Title: "6. Downloading and Preparing GLPI",
        etape6Text1: "The next step is to download the \".tgz\" archive that contains the GLPI installation sources. From the GLPI GitHub, retrieve the link to the latest version. Here, it is GLPI version 10.0.10 that is installed.",
        etape6Text2: "Then, we will execute the command below to decompress the .tgz archive in the \"/var/www/\" directory, which will give the access path \"/var/www/glpi\" for GLPI.",
        etape6Text3: "We will define the \"www-data\" user corresponding to Apache2, as owner on the GLPI files.",
        etape6Text4: "Then, we will have to create several folders and remove data from the Web root (/var/www/glpi) in order to store them in the new folders that we will create. This will allow for a secure installation of GLPI, which follows the publisher's recommendations.",
        etape6H5_1: "The /etc/glpi directory",
        etape6Text5: "Start by creating the \"/etc/glpi\" directory which will receive the GLPI configuration files. We give permissions to www-data on this directory because it needs to be able to access it.",
        etape6Text6: "Then, we will move the \"config\" directory of GLPI to this new folder:",
        etape6H5_2: "The /var/lib/glpi directory",
        etape6Text7: "Let's repeat the same operation with the creation of the \"/var/lib/glpi\" directory:",
        etape6Text8: "In which we also move the \"files\" folder which contains most of the GLPI files: CSS, plugins, etc.",
        etape6H5_3: "The /var/log/glpi directory",
        etape6Text9: "Let's finish with the creation of the \"/var/log/glpi\" directory intended to store the GLPI logs. Always on the same principle:",
        etape6Text10: "We have nothing to move in this directory.",
        etape6H5_4: "Create the configuration files",
        etape6Text11: "We need to configure GLPI so that it knows where to look for the data. In other words, we will declare the newly created directories",
        etape6Text12: "We will create this first file:",
        etape6Text13: "To add the content below which indicates the path to the configuration directory:",
        etape6Text14: "Then, we will create this second file:",
        etape6Text15: "To add the content below allowing to declare two variables to specify the paths to the \"files\" and \"log\" directories that we prepared previously.",
        etape6Text16: "There, this step is completed.",
        etape7Title: "7. Apache Configuration with VirtualHost",
        etape7Text1: "Let's move on to the configuration of the Apache2 web server. We will create a new configuration file that will allow us to configure the VirtualHost dedicated to GLPI.",
        etape7Text2: "Which gives the following configuration:",
        etape7Text3: "When the configuration is ready, save the file.",
        etape7Text4: "Then, we will activate this new site in Apache2:",
        etape7Text5: "We also take the opportunity to disable the default site because it is useless:",
        etape7Text6: "We will also enable the \"rewrite\" module (for rewrite rules) because we used it in the VirtualHost configuration file (RewriteCond / RewriteRule).",
        etape7Text7: "All that remains is to restart the Apache2 service:",
        etape8Title: "8. PHP-FPM Configuration and Required Extensions",
        etape8Text1: "To use PHP as a script engine with Apache2, there are two possibilities: use the PHP module for Apache2 (libapache2-mod-php8.2) or use PHP-FPM.",
        etape8Text2: "It is recommended to use PHP-FPM because it is more performant and presents itself as an independent service. In the other mode, each Apache2 process runs its own PHP script engine.",
        etape8Text3: "If you want to use PHP-FPM, follow the steps below. Otherwise, skip to the next but be sure to configure the \"session.cookie_httponly\" option mentioned below.",
        etape8Text4: "We will start by installing PHP8.2-FPM with the following command:",
        etape8Text5: "Then, we will enable two modules in Apache and the PHP-FPM configuration, before reloading Apache2:",
        etape8Text6: "To configure PHP-FPM for Apache2, we will not edit the \"/etc/php/8.2/apache2/php.ini\" file but rather this file:",
        etape8Text7: "In this file, search for the \"session.cookie_httponly\" option and set the value \"on\" to activate it, in order to protect GLPI cookies.",
        etape8Text8: "Save the file when done. Later, you may need to make other modifications, notably to increase the upload size on GLPI, etc. To apply the changes, we must restart PHP-FPM:",
        etape8Text9: "Finally, we must modify our VirtualHost to specify to Apache2 that PHP-FPM must be used for PHP files:",
        etape8Text10: "Here is an example:",
        etape8Text11: "When done, restart Apache2:",
        etape9Title: "9. Installation via Web Browser",
        etape9Text1: "To perform the GLPI installation, Access <code>http://YOUR_VM_IP</code> and follow the steps:",
        etape9List1: "Language choice",
        etape9List2: "Prerequisites check (all must be green)",
        etape9List3: "Database connection: <code>glpi_db</code>, user <code>glpi_user</code>",
        etape9List4: "Tables creation",
        etape9List5: "End of installation",
        etape9Text2: "<strong>⚠️ Security:</strong> Immediately delete the installation script:",
        etape10Title: "10. First Login and Security",
        etape10Text1: "Default accounts:",
        etape10List1: "<strong>Admin</strong>: <code>glpi</code> / <code>glpi</code>",
        etape10List2: "<strong>Technician</strong>: <code>tech</code> / <code>tech</code>",
        etape10List3: "<strong>Normal user</strong>: <code>normal</code> / <code>normal</code>",
        etape10List4: "<strong>Post-only</strong>: <code>post-only</code> / <code>postonly</code>",
        etape10Text2: "➡️ Change **all passwords** after the first login.",
        etape11Title: "11. Post-Installation Best Practices",
        etape11List1: "🔐 Enable HTTPS with Let’s Encrypt",
        etape11List2: "🔄 Update GLPI and PHP regularly",
        etape11List3: "💾 Backup the database: <code>mysqldump -u root -p glpi_db > /backup/glpi_$(date +%F).sql</code>",
        etape11List4: "🧩 Install useful plugins: FusionInventory, LDAP, PDF, etc.",
        etape11List5: "🛡️ Restrict access to the admin interface by IP",
        etape12Title: "12. Conclusion",
        etape12Text1: "You now have a secure and functional instance of GLPI on Debian 12. This system allows you to efficiently manage your IT assets, support tickets, and resources.",
        etape12Text2: "To go further: LDAP integration, monitoring, inventory automation with FusionInventory."
    },
    ar: {
        title: "دليل تثبيت وتكوين GLPI على Debian 12 (VMware)",
        sommaireTitle: "جدول المحتويات",
        sommaireItem1: "1. مقدمة عن GLPI",
        sommaireItem2: "2. المتطلبات الرسمية لـ GLPI",
        sommaireItem3: "3. إعداد خادم Debian 12",
        sommaireItem4: "4. تثبيت قاعدة LAMP",
        sommaireItem5: "5. تكوين MariaDB الآمن",
        sommaireItem6: "6. تنزيل وإعداد GLPI",
        sommaireItem7: "7. تكوين Apache مع VirtualHost",
        sommaireItem8: "8. تكوين PHP-FPM والإضافات المطلوبة",
        sommaireItem9: "9. التثبيت عبر متصفح الويب",
        sommaireItem10: "10. الاتصال الأول والأمان",
        sommaireItem11: "11. أفضل الممارسات بعد التثبيت",
        sommaireItem12: "12. الخاتمة",
        etape1Title: "1. مقدمة عن GLPI",
        etape1Text1: "GLPI (مدير أصول تكنولوجيا المعلومات المجاني) هو برنامج مفتوح المصدر لإدارة أصول تكنولوجيا المعلومات، يوفر حلاً شاملاً لإدارة المعدات (الحواسيب، الهواتف، الأجهزة الطرفية)، تتبع تذاكر الدعم، بالإضافة إلى إدارة العقود والتراخيص والموارد المادية.",
        etape1Text2: "منذ إنشائه في عام 2003، أصبح GLPI حلاً موثوقًا ومقبولاً على نطاق واسع. يرشدك هذا الدليل خطوة بخطوة في تثبيته على <strong>Debian 12</strong> مع بيئة <strong>LAMP</strong> تحت VMware.",
        etape1H3: "عرض GLPI",
        etape2Title: "2. المتطلبات الأساسية لتثبيت GLPI",
        etape2Text1: "قبل المتابعة في التثبيت، من المهم التحقق من أن بيئتك تلبي المتطلبات اللازمة. يتطلب GLPI خادم ويب وPHP وقاعدة بيانات ليعمل بشكل صحيح. على نظام Linux، يتوافق هذا عمومًا مع بنية LAMP. GLPI متوافق مع عدة خوادم ويب، بما في ذلك:",
        etape2List1: "Apache2، Nginx، Lighttpd، وIIS",
        etape2H5_1: "الإصدارات المطلوبة",
        etape2H7_1: "● PHP",
        etape2PhpList: "الإصدار: 8.2",
        etape2H7_2: "● قاعدة البيانات",
        etape2DbList1: "MySQL: الإصدار 5.1 الحد الأدنى",
        etape2DbList2: "MariaDB: الإصدار 10.2 الحد الأدنى",
        etape2Text2: "لاحظ أيضًا أن عدة إضافات PHP يجب تثبيتها لضمان عمل GLPI بشكل صحيح.",
        etape2Text3: "الإصدار الأخير المتاح حتى الآن، <strong>GLPI 10.0.10</strong>، يقدم دعم PHP 8.3 (الإصدار المستقبلي المستقر) وMySQL 8.1، مع إصلاح العديد من الثغرات الحرجة.",
        etape2Text4: "لهذه العرض، سنستخدم جهازًا يعمل بنظام <strong>Debian 12</strong>، والذي سنثبت عليه <strong>Apache2</strong>، <strong>PHP 8.3</strong>، و<strong>MariaDB</strong>.",
        etape2Text5: "لمزيد من التفاصيل، يمكنك استشارة <a href=\"https://glpi-install.readthedocs.io/en/latest/prerequisites.html\" target=\"_blank\">الوثائق الرسمية لمتطلبات GLPI</a>.",
        etape3Title: "3. إعداد خادم Debian 12",
        etape3Text1: "دعنا نبدأ التثبيت بتحديث الحزم على جهاز Debian 12. تذكر أيضًا تخصيص عنوان IP وإجراء تكوين النظام",
        etape4Title: "4. تثبيت قاعدة LAMP",
        etape4Text1: "الخطوة الرئيسية الأولى هي تثبيت حزم قاعدة LAMP: Linux Apache2 MariaDB PHP. تحت Debian 12، والتي هي الإصدار المستقر الأخير لـ Debian، يتم توزيع PHP 8.2 افتراضيًا في المستودعات الرسمية. دعنا نبدأ بتثبيت هذه الحزم الثلاث:",
        etape4Text2: "ثم، سنثبت جميع الإضافات اللازمة لعمل GLPI بشكل صحيح.",
        etape4Text3: "ستسمح هذه الأوامر باستعادة إصدارات هذه الإضافات لـ PHP 8.2.",
        etape4Text4: " إذا كنت تخطط لربط GLPI بدليل LDAP مثل Active Directory، يجب تثبيت إضافة LDAP لـ PHP. خلاف ذلك، ليس ضروريًا ويمكنك القيام بذلك لاحقًا إذا لزم الأمر.",
        etape4Text5: "لقد قمنا للتو بتثبيت Apache2، MariaDB، PHP ومجموعة من الإضافات.",
        etape5Title: "5. تكوين MariaDB الآمن",
        etape5Text1: "سنعد MariaDB حتى يتمكن من استضافة قاعدة بيانات GLPI. الإجراء الأول الذي يجب القيام به هو تشغيل الأمر أدناه لأداء الحد الأدنى من الأمان لـ MariaDB.",
        etape5Text2: "سيتم دعوتك لتغيير كلمة مرور الجذر، ولكن أيضًا لحذف المستخدمين المجهولين، تعطيل الوصول عن بعد للجذر، إلخ... كل شيء موضح جيدًا. إليك مثال على خادمي لإرشادك:",
        etape5Text3: "ثم، سننشئ قاعدة بيانات مخصصة لـ GLPI وسيتم الوصول إليها بواسطة مستخدم مخصص. لا طريقة لاستخدام حساب الجذر في MariaDB: قاعدة بيانات واحدة = مستخدم واحد. قم بالاتصال بحالة MariaDB الخاصة بك:",
        etape5Text4: "أدخل كلمة مرور جذر MariaDB، والتي حددتها للتو في الخطوة السابقة.",
        etape5Text5: "ثم، سننفذ الاستعلامات SQL أدناه لإنشاء قاعدة البيانات \"db23_glpi\" بالإضافة إلى المستخدم \"glpi_adm\" بكلمة المرور \"MotDePasseRobuste\" (التي تغيرها، بالطبع). سيكون لهذا المستخدم جميع الحقوق على هذه قاعدة البيانات (وعليها فقط).",
        etape5Text6: "الذي يعطي:",
        etape5Text7: "هناك، قاعدة البيانات جاهزة.",
        etape6Title: "6. تنزيل وإعداد GLPI",
        etape6Text1: "الخطوة التالية هي تنزيل أرشيف \".tgz\" الذي يحتوي على مصادر تثبيت GLPI. من GitHub الخاص بـ GLPI، استرجع الرابط إلى الإصدار الأخير. هنا، هو إصدار GLPI 10.0.10 الذي تم تثبيته.",
        etape6Text2: "ثم، سننفذ الأمر أدناه لفك ضغط أرشيف .tgz في الدليل \"/var/www/\"، والذي سيعطي مسار الوصول \"/var/www/glpi\" لـ GLPI.",
        etape6Text3: "سنحدد المستخدم \"www-data\" المقابل لـ Apache2، كمالك على ملفات GLPI.",
        etape6Text4: "ثم، سنضطر إلى إنشاء عدة مجلدات وإزالة البيانات من جذر الويب (/var/www/glpi) لتخزينها في المجلدات الجديدة التي سننشئها. سيسمح هذا بتثبيت آمن لـ GLPI، يتبع توصيات الناشر.",
        etape6H5_1: "الدليل /etc/glpi",
        etape6Text5: "ابدأ بإنشاء الدليل \"/etc/glpi\" الذي سيتلقى ملفات تكوين GLPI. نعطي الإذن لـ www-data على هذا الدليل لأنه يحتاج إلى القدرة على الوصول إليه.",
        etape6Text6: "ثم، سننقل دليل \"config\" الخاص بـ GLPI إلى هذا المجلد الجديد:",
        etape6H5_2: "الدليل /var/lib/glpi",
        etape6Text7: "دعنا نكرر العملية نفسها مع إنشاء الدليل \"/var/lib/glpi\":",
        etape6Text8: "الذي ننقل فيه أيضًا مجلد \"files\" الذي يحتوي على غالبية ملفات GLPI: CSS، الإضافات، إلخ.",
        etape6H5_3: "الدليل /var/log/glpi",
        etape6Text9: "دعنا ننهي بإنشاء الدليل \"/var/log/glpi\" المخصص لتخزين سجلات GLPI. دائمًا على نفس المبدأ:",
        etape6Text10: "ليس لدينا شيء لنقله في هذا الدليل.",
        etape6H5_4: "إنشاء ملفات التكوين",
        etape6Text11: "يجب أن نكون GLPI حتى يعرف أين يبحث عن البيانات. بمعنى آخر، سنعلن الدلائل الجديدة التي تم إنشاؤها",
        etape6Text12: "سننشئ هذا الملف الأول:",
        etape6Text13: "لإضافة المحتوى أدناه الذي يشير إلى المسار إلى دليل التكوين:",
        etape6Text14: "ثم، سننشئ هذا الملف الثاني:",
        etape6Text15: "لإضافة المحتوى أدناه الذي يسمح بإعلان متغيرين لتحديد المسارات إلى الدليلين \"files\" و \"log\" اللذين أعددناهما سابقًا.",
        etape6Text16: "هناك، هذه الخطوة مكتملة.",
        etape7Title: "7. تكوين Apache مع VirtualHost",
        etape7Text1: "دعنا ننتقل إلى تكوين خادم الويب Apache2. سننشئ ملف تكوين جديد سيسمح لنا بتكوين VirtualHost المخصص لـ GLPI.",
        etape7Text2: "الذي يعطي التكوين التالي:",
        etape7Text3: "عندما يكون التكوين جاهزًا، احفظ الملف.",
        etape7Text4: "ثم، سنفعل هذا الموقع الجديد في Apache2:",
        etape7Text5: "نستفيد أيضًا من الفرصة لتعطيل الموقع الافتراضي لأنه غير مفيد:",
        etape7Text6: "سنفعل أيضًا وحدة \"rewrite\" (لقواعد إعادة الكتابة) لأننا استخدمناها في ملف تكوين VirtualHost (RewriteCond / RewriteRule).",
        etape7Text7: "كل ما تبقى هو إعادة تشغيل خدمة Apache2:",
        etape8Title: "8. تكوين PHP-FPM والإضافات المطلوبة",
        etape8Text1: "لاستخدام PHP كمحرك نصوص مع Apache2، هناك احتماليتان: استخدام وحدة PHP لـ Apache2 (libapache2-mod-php8.2) أو استخدام PHP-FPM.",
        etape8Text2: "يوصى باستخدام PHP-FPM لأنه أكثر أداءً ويقدم نفسه كخدمة مستقلة. في الوضع الآخر، يقوم كل عملية Apache2 بتشغيل محرك نصوص PHP الخاص بها.",
        etape8Text3: "إذا كنت ترغب في استخدام PHP-FPM، اتبع الخطوات أدناه. خلاف ذلك، انتقل إلى التالي ولكن تأكد من تكوين الخيار \"session.cookie_httponly\" المذكور أدناه.",
        etape8Text4: "سنبدأ بتثبيت PHP8.2-FPM بالأمر التالي:",
        etape8Text5: "ثم، سنفعل وحدتين في Apache وتكوين PHP-FPM، قبل إعادة تحميل Apache2:",
        etape8Text6: "لتكوين PHP-FPM لـ Apache2، لن نحرر الملف \"/etc/php/8.2/apache2/php.ini\" ولكن بدلاً من ذلك هذا الملف:",
        etape8Text7: "في هذا الملف، ابحث عن الخيار \"session.cookie_httponly\" وقم بتعيين القيمة \"on\" لتفعيله، من أجل حماية كوكيز GLPI.",
        etape8Text8: "احفظ الملف عند الانتهاء. لاحقًا، قد تحتاج إلى إجراء تعديلات أخرى، خاصة لزيادة حجم التحميلات على GLPI، إلخ. لتطبيق التغييرات، يجب إعادة تشغيل PHP-FPM:",
        etape8Text9: "أخيرًا، يجب تعديل VirtualHost الخاص بنا لتحديد لـ Apache2 أن PHP-FPM يجب استخدامه لملفات PHP:",
        etape8Text10: "إليك مثال:",
        etape8Text11: "عند الانتهاء، أعد تشغيل Apache2:",
        etape9Title: "9. التثبيت عبر متصفح الويب",
        etape9Text1: "لإجراء تثبيت GLPI، قم بالوصول إلى <code>http://IP_DE_VOTRE_VM</code> واتبع الخطوات:",
        etape9List1: "اختيار اللغة",
        etape9List2: "التحقق من المتطلبات (يجب أن تكون جميعها خضراء)",
        etape9List3: "الاتصال بقاعدة البيانات: <code>glpi_db</code>، المستخدم <code>glpi_user</code>",
        etape9List4: "إنشاء الجداول",
        etape9List5: "نهاية التثبيت",
        etape9Text2: "<strong>⚠️ الأمان:</strong> احذف فورًا سكريبت التثبيت:",
        etape10Title: "10. الاتصال الأول والأمان",
        etape10Text1: "الحسابات الافتراضية:",
        etape10List1: "<strong>المشرف</strong>: <code>glpi</code> / <code>glpi</code>",
        etape10List2: "<strong>الفني</strong>: <code>tech</code> / <code>tech</code>",
        etape10List3: "<strong>المستخدم العادي</strong>: <code>normal</code> / <code>normal</code>",
        etape10List4: "<strong>النشر فقط</strong>: <code>post-only</code> / <code>postonly</code>",
        etape10Text2: "➡️ غير **جميع كلمات المرور** بعد الاتصال الأول.",
        etape11Title: "11. أفضل الممارسات بعد التثبيت",
        etape11List1: "🔐 تفعيل HTTPS مع Let’s Encrypt",
        etape11List2: "🔄 تحديث GLPI وPHP بانتظام",
        etape11List3: "💾 نسخ احتياطي لقاعدة البيانات: <code>mysqldump -u root -p glpi_db > /backup/glpi_$(date +%F).sql</code>",
        etape11List4: "🧩 تثبيت إضافات مفيدة: FusionInventory، LDAP، PDF، إلخ.",
        etape11List5: "🛡️ تقييد الوصول إلى واجهة المشرف بواسطة IP",
        etape12Title: "12. الخاتمة",
        etape12Text1: "لديك الآن نسخة آمنة ووظيفية من GLPI على Debian 12. يسمح لك هذا النظام بإدارة أصول تكنولوجيا المعلومات الخاصة بك، تذاكر الدعم، والموارد بكفاءة.",
        etape12Text2: "للذهاب أبعد: دمج LDAP، الرصد، أتمتة الجرد مع FusionInventory."
    }
};

// Fonction pour changer la langue et la direction
function setLanguage(lang) {
    document.querySelectorAll("[data-lang]").forEach(el => {
        const key = el.getAttribute("data-lang");
        if (translations[lang][key]) {
            if (Array.isArray(translations[lang][key])) {
                el.innerHTML = translations[lang][key].map(item => `<li>${item}</li>`).join('');
            } else {
                el.innerHTML = translations[lang][key];  // Use innerHTML to preserve <strong> tags etc.
            }
        }
    });

 if (lang === "ar") {
    document.body.setAttribute("dir", "rtl");
    document.body.style.direction = "rtl";
} else {
    document.body.setAttribute("dir", "ltr");
    document.body.style.direction = "ltr";
}
}